app:
  host: "localhost"
  port: 8080
  tlscert: ""
  tlskey: ""
  logLevel: "debug"
  archivePath: "/"

session:
  # session key expiration time in seconds
  # default value = -1 for disabled state
  # a positive integer enables sessions
  # a negative integer disables sessions
  expiration: 28800
  # domain name must be set to the hostname (FQDN) of the service
  domain: "localhost"

c4gh:
  filepath: "test/doa.sec.pem"
  passphrase: "doa"

db:
  host: "localhost"
  user: "lega_out"
  password: "lega_out"
  database: "lega"
  cacert: ""
  clientCert: ""
  clientKey: ""
  sslmode: "require"

oidc:
  ConfigurationURL: "https://login.elixir-czech.org/oidc/.well-known/openid-configuration"
