app:
  host: "localhost"
  port: 8080
  tlscert: "test/tls.crt"
  tlskey: "test/tls.key"
  logLevel: "debug"
  archivePath: "/"

session:
  # session key expiration time in seconds
  # default value = -1 for disabled state
  # a positive integer enables sessions
  # a negative integer disables sessions
  expiration: 28800
  # domain name must be set to the hostname (FQDN) of the service
  domain: "localhost"
  # session cookie Secure value, if true, TLS must be active
  # default value = true
  secure: true
  # session cookie HttpOnly value, if true, TLS must be active
  # default value = true
  httponly: true

c4gh:
  # crypt4gh private key for decrypting archived files
  filepath: "test/doa.sec.pem"
  passphrase: "doa"

db:
  host: "localhost"
  user: "lega_out"
  password: "lega_out"
  database: "lega"
  cacert: ""
  clientCert: ""
  clientKey: ""
  sslmode: "require"

oidc:
  # oidc configuration API must have values for "userinfo_endpoint" and "jwks_uri"
  ConfigurationURL: "https://login.elixir-czech.org/oidc/.well-known/openid-configuration"
