app:
  host: "localhost"
  port: 8080
  tlscert: ""
  tlskey: ""
  logLevel: "debug"
  archivePath: "/"

session:
  # session key expiration time in seconds
  # default 28800 = 8 hours
  # -1 = sessions are disabled and auth is required on every request
  expiration: 28800
  # domain name must be set to the FQDN hostname of the service
  domain: "localhost"

c4gh:
  filepath: "test/doa.sec.pem"
  passphrase: "doa"

db:
  host: "localhost"
  user: "lega_out"
  password: "lega_out"
  database: "lega"
  cacert: ""
  clientCert: ""
  clientKey: ""
  sslmode: "require"

oidc:
  ConfigurationURL: "https://login.elixir-czech.org/oidc/.well-known/openid-configuration"
