version: "3.7"
services:
  db:
    command: server /data
    container_name: db
    environment:
      - DB_LEGA_IN_PASSWORD=lega_in
      - DB_LEGA_OUT_PASSWORD=lega_out
      - NOTLS=true
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "lega_out"]
      interval: 5s
      timeout: 20s
      retries: 3
    image: neicnordic/sda-db:v1.4.0
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/data
  s3:
    command: server /data
    container_name: s3
    environment:
      - MINIO_ACCESS_KEY=access
      - MINIO_SECRET_KEY=secretkey
    healthcheck:
      test: ["CMD", "curl", "-fq", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 20s
      retries: 3
    image: minio/minio:RELEASE.2021-11-24T23-19-33Z
    ports:
      - "9000:9000"
  createbucket:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add s3 http://s3:9000 access secretkey;
      /usr/bin/mc mb s3/archive || true;
      exit 0;
      "
  download:
    command: sda-download
    container_name: download
    depends_on: 
      - db
      - s3
    environment:
      - ARCHIVE_URL=http://s3
      - ARCHIVE_TYPE=s3
      - DB_HOST=db
    image: neicnordic/sda-download:latest
    volumes:
      - ./config-notls.yaml:/config.yaml
      - ./:/dev_utils/
      - ./archive_data:/tmp
    ports:
      - "8080:8080"
    restart: always

volumes:
     archive:
