name: Multilinters

on:
  push:

jobs:

  build:
    name: Check code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17, 1.18]
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.45
          args: -E gosec,goconst,nestif,bodyclose,rowserrcheck
